### ISSUE TITLE
Test ODK form - locations section - can you go backwards? 

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/holpa-platform#37]

**Comment by dan-tang-ssd** [comment]
We have a testing ODK form with below location levels:
District > Sub-district > Village > Farm

I did some testing in ODK Collect. I selected one level further each time then go backward.
There is issue at District and Sub-district level.

Below please find screen shots for my four test cases FYI.

**Comment by dan-tang-ssd** [comment]
Test 1 - Select district only

Screen shots:

![Screenshot_20241118-112157](https://github.com/user-attachments/assets/5fe478cf-9a9d-4ac8-be7d-b9ae20a0289a)

![Screenshot_20241118-112203](https://github.com/user-attachments/assets/b4cd197a-8dfa-4555-bb34-8cef64e7d650)

![Screenshot_20241118-112206](https://github.com/user-attachments/assets/2238da2a-c4f5-47a2-8251-839661ac62fe)

![Screenshot_20241118-112214](https://github.com/user-attachments/assets/1bd41579-bd3b-4663-bf3f-1629bf43b060)

**Comment by dan-tang-ssd** [comment]
Test 2 - Select up to sub-district

Screen shots:

![Screenshot_20241118-112319](https://github.com/user-attachments/assets/231f894d-a47b-4721-b1c0-bcda297fe677)

![Screenshot_20241118-112324](https://github.com/user-attachments/assets/a6374c0e-c2a8-49aa-87e1-af0ec7314519)

![Screenshot_20241118-112339](https://github.com/user-attachments/assets/73b00c82-ccf3-4dc1-adb7-a051bf0a067e)

![Screenshot_20241118-112345](https://github.com/user-attachments/assets/ba5b0ea5-d4b3-46f0-9db3-99271c93dd12)

![Screenshot_20241118-112349](https://github.com/user-attachments/assets/01bfe08d-d699-4518-a4d4-a80d72c6b139)

**Comment by dan-tang-ssd** [comment]
Test 3 - Select up to village

Screen shots:

![Screenshot_20241118-113833](https://github.com/user-attachments/assets/b74407d5-e219-492a-83f6-a2567a4f5a1f)

![Screenshot_20241118-113843](https://github.com/user-attachments/assets/72b41761-fce2-451d-8069-f9bb6b511638)

![Screenshot_20241118-113848](https://github.com/user-attachments/assets/b53a3dc3-bbec-4173-965a-438d6132ac7e)

![Screenshot_20241118-113857](https://github.com/user-attachments/assets/7038e963-3f2b-46dd-8d07-0671b1537294)

![Screenshot_20241118-113903](https://github.com/user-attachments/assets/9d499ed1-b24f-4835-8cc4-fd47e4133627)

![Screenshot_20241118-113907](https://github.com/user-attachments/assets/0d2833f4-1b7f-4618-8c19-cdbf6366051a)

![Screenshot_20241118-113911](https://github.com/user-attachments/assets/49ffc250-9da2-421a-80a5-b435cb157101)

**Comment by dan-tang-ssd** [comment]
Test 4 - Select up to farm

Screen shots:

![Screenshot_20241118-114030](https://github.com/user-attachments/assets/7517521d-ab43-4e58-a843-d37e89b66a1a)

![Screenshot_20241118-114036](https://github.com/user-attachments/assets/6353b056-bf90-4fcb-a98b-4d819cc39e84)

![Screenshot_20241118-114041](https://github.com/user-attachments/assets/1008d9f7-bb69-4fdb-8df7-25bdc718558c)

![Screenshot_20241118-114050](https://github.com/user-attachments/assets/f04a2cc0-3a37-4a64-82ce-5bc741d779b4)

![Screenshot_20241118-114054](https://github.com/user-attachments/assets/e76e9655-c82b-42dd-8f9e-f16cca853135)

![Screenshot_20241118-114059](https://github.com/user-attachments/assets/4a2a59dc-ae6c-4209-a0f6-5714e6249420)

![Screenshot_20241118-114103](https://github.com/user-attachments/assets/38156f55-f3ac-4bf3-8fbc-b83d511ccb94)

![Screenshot_20241118-114107](https://github.com/user-attachments/assets/0f66c70a-bf7a-416a-84a6-c20f62b4550f)

**Comment by alex-thomson222** [comment]
[location selection test.xlsx](https://github.com/user-attachments/files/17800507/location.selection.test.xlsx)

Hi Dan,

Through a lot of trial and error, Dave and I have managed to figure out how to fix this issue. I have attached an updated xlsform snippet for the location selection. Ultimately it was an issue of how and when a certain calculation gets triggered.

Alex

**Comment by dan-tang-ssd** [comment]
Thank you Alex.

I am going to perform testing for the updated xlsform.
I will let you know once I have testing result.

**Comment by dan-tang-ssd** [comment]
@dave-mills - I got issue when deploying the updated xlsform to ODK central...

Here are what I did:
1. get latest code from dev branch
2. run command "composer install", "npm i", "npm run build", "npm run dev"
3. run command "php artisan migrate:fresh --seed"
4. download the updated xlsform, add settings excel sheet to it
5. login as admin, create a new team, create xlsform template
6. admin panel > team resources > xlsforms relation manager, click "Add Xlsform to Team" button to add xlsform, error 500 occurred

I create another xlsform template with our previous xlsform, got same error.

---

Screen shot:

![image](https://github.com/user-attachments/assets/dac5abf9-709c-4dc4-92e0-a5cf58a317c0)

**Comment by dave-mills** [comment]
@dan-tang-ssd oh wait - you're adding the xlsform template to a team! I didn't realise that, as that's not needed to test the form. Let me check locally too.

**Comment by dan-tang-ssd** [comment]
I have submitted the latest ODK form to ODK central staging server, then download the form in ODK Collect for testing.
https://odk-test.stats4sdtest.online/#/projects/1000/forms/location_selection_test/draft/testing

The ODK form now works very well. I can go back to modify location in any level.
This is to confirm the issue is resolved.
