### ISSUE TITLE
Remove `xlsfile` references

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/holpa-platform#41]
It looks like the ODK Link Package still references `xlsfile` as a property of Xlsform and XlsformTemplate models, but we have moved to Spatie Media library collections to store the actual Excel files. This is causing at least one error (described below): 

Context: 

@dave-mills - I got issue when deploying the updated xlsform to ODK central...

Here are what I did:
1. get latest code from dev branch
2. run command "composer install", "npm i", "npm run build", "npm run dev"
3. run command "php artisan migrate:fresh --seed"
4. download the updated xlsform, add settings excel sheet to it
5. login as admin, create a new team, create xlsform template
6. admin panel > team resources > xlsforms relation manager, click "Add Xlsform to Team" button to add xlsform, error 500 occurred

I create another xlsform template with our previous xlsform, got same error.

---

Screen shot:

![image](https://github.com/user-attachments/assets/dac5abf9-709c-4dc4-92e0-a5cf58a317c0)

_Originally posted by @dan-tang-ssd in https://github.com/stats4sd/holpa-platform/issues/37#issuecomment-2483215881_

**Comment by dave-mills** [comment]
The issue here isn't what I thought it was. The current setup already handles the Spatie media library well - the `Xlsform` and `XlsformTemplate` have a computed attribute `xlsfile`, which is defined as: 

```php
public function xlsfile(): Attribute
    {
        return new Attribute(
            get: fn(): string => $this->getFirstMediaPath('xlsform_file'),
        );
    }
```

I realised this because the same Job class was working fine when creating an XlsformTemplate but not an Xlsform. 

The problem here is a namespace clash. The media item is being linked to `App\Models\XlsformTemplate`, but when the `FilamentOdkLink\Models\OdkLink\Xlsform` is created, it tries to copy the media item from `FilamentOdkLInk\Models\OdkLink\XlsformTemplate`... so the media item is not found. 

One possible solution here is to do what we did with the team management and add a config setting so we can specify the exact XlsformTemplate model to use per-app. That will mean a lot of changes to the package, which is already pretty messy, and I don't know right now if that's the best approach in the short term.

**Comment by dave-mills** [comment]
A short-term option is to bring it all together into one namespace. A lot of what we're doing for HOLPA as "custom" functionality is actually stuff we will probably use across many apps in the future, so it might make sense to bring it all together into the `App`, then take it back out into the package in the new year.

**Comment by dave-mills** [comment]
@dan-tang-ssd  - I've submitted a hotfix for this - it's not a permanent solution, but it will get us to a working system quickly and give us time to consider the architecture of the package + app combo more carefully before making any major decisions. 

See: 
- Package - https://github.com/stats4sd/filament-odk-link/pull/46
- App - https://github.com/stats4sd/holpa-platform/pull/63

**Comment by dan-tang-ssd** [comment]
The issue has been resolved. 

I think this issue can be closed.
