### ISSUE TITLE
Setup survey monitoring page for teams

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/holpa-platform#51]
Exact requirements to be discussed, but initial thoughts: 

- Number of submissions per form;
- Number of "completed" surveys (i.e. farms with 1 submission for both forms)
- Number of completed surveys split by location;
- Timestamp of latest survey submitted.

Submission list:
- View data;
- Edit data (in Enketo); - get the updated data from ODK central.
- Download data

**Comment by dave-mills** [comment]
@alex-thomson222 - the above is based on the survey monitoring page we did for the TAPE Beta platform, but I would like your input on what would be useful for implementing teams to see when conducting a survey. Dan can comment on what is quick to do, so hopefully between you you can get to a set of things for a dashboard that is both useful and quick to build.

**Comment by alex-thomson222** [comment]
I think you have the main things covered already

Possibly depending on how enumerators are defined/hired , they may wish to see the number of surveys by enumerator so they can monitor that a bit more closely. 

One thing that may be a bit harder to do (though I wonder if it can be shortcut-ed using ODK) is showing how many forms were completed in an unreasonably short time such as less than 10 minutes for the household and less than 5 minutes for the fieldwork. Completing the survey that rapidly is very unlikely and suggestive of poor data quality and they may wish to investigate these instances.

**Comment by dan-tang-ssd** [comment]
@dave-mills  - I am reviewing the current survey monitoring page.

I would like to keep items highlighted in GREEN.

Questions:
1. Do we need"Beneficiary Farms" and "Non-Beneficiary Farms" for holpa? If no, can I remove them?
2. Can I add "Farms Fully Surveyed" to show number of farms with household form completed and fieldwork form completed?
3. In submission_summary_wrapper, it has "Submission by Locations" and "Submission by Enumerators". I will keep them.
4. In submission_summary_wrapper, I will add "Submission by Duration", to show number of submissions with survey duration <5, <30, <60, <120 and >120 minutes. Any concern if I add columns survey_started_at, survey_ended_at, survey_duration to submissions table?

---

Screen shots:

![image](https://github.com/user-attachments/assets/5704f1bd-faf7-43d8-9fc4-51c6e6f51e50)

**Comment by dave-mills** [comment]
> 1. Do we need"Beneficiary Farms" and "Non-Beneficiary Farms" for holpa? If no, can I remove them?

No. Each team will have different disaggregations, and for now we will leave it up to the teams to handle that offline / with the data exports. 

> 2. Can I add "Farms Fully Surveyed" to show number of farms with household form completed and fieldwork form completed?

Yes please, as that's one of the requirements!

> 3. In submission_summary_wrapper, it has "Submission by Locations" and "Submission by Enumerators". I will keep them.

👍 

> 4. In submission_summary_wrapper, I will add "Submission by Duration", to show number of submissions with survey duration <5, <30, <60, <120 and >120 minutes. Any concern if I add columns survey_started_at, survey_ended_at, survey_duration to submissions table?

As Alex mentioned, the only real value in seeing the survey duration is for very short durations. I would say we only want to highlight surveys that are <10 minutes. I would suggest this is a good option for a filter on the main submissions table, so that reviewers can quickly check the data quality of those submissions as well.

**Comment by dave-mills** [comment]
Update: hide enumerator section for now; maybe add later if important for teams
