### ISSUE TITLE
generate a bunch of submission data

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/holpa-platform#74]
For both surveys

**Comment by alex-thomson222** [comment]
Currently submitted 2 entries for each survey, will continue filling a few more.

**Comment by dave-mills** [comment]
@alex-thomson222 @dan-tang-ssd  - marking this as done 👍

**Comment by alex-thomson222** [comment]
I would say i was probably going to try to do some more later on now that the outstanding issues are fixed as that additionally fixes some data issues i need for testing the r scripts.

- which btw is the issue of missing data after income_count being corrected for existing submissions? seems most of the calculations i need to test are for variables after this
